// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'database.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:User.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// User TABLE
class TableUser extends SqfEntityTableBase {
  TableUser() {
    // declare properties of EntityTable
    tableName = 'user';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('email', DbType.text, isUnique: true),
      SqfEntityFieldBase('password', DbType.text),
      SqfEntityFieldBase('isSignIN', DbType.bool, defaultValue: true),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableUser();
  }
}

// Ticket TABLE
class TableTicket extends SqfEntityTableBase {
  TableTicket() {
    // declare properties of EntityTable
    tableName = 'ticket';
    primaryKeyName = 'ticketID';
    primaryKeyType = PrimaryKeyType.integer_unique;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('movieID', DbType.integer),
      SqfEntityFieldBase('customerName', DbType.text),
      SqfEntityFieldBase('email', DbType.text),
      SqfEntityFieldBase('customerID', DbType.integer),
      SqfEntityFieldBase('contactNumber', DbType.integer),
      SqfEntityFieldBase('movieTitle', DbType.text),
      SqfEntityFieldBase('url', DbType.text),
      SqfEntityFieldBase('movieStartTime', DbType.integer),
      SqfEntityFieldBase('movieEndTime', DbType.integer),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableTicket();
  }
}

// History TABLE
class TableHistory extends SqfEntityTableBase {
  TableHistory() {
    // declare properties of EntityTable
    tableName = 'history';
    primaryKeyName = 'movieID';
    primaryKeyType = PrimaryKeyType.integer_unique;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('url', DbType.text),
      SqfEntityFieldBase('searchAt', DbType.integer, isUnique: true),
      SqfEntityFieldBase('title', DbType.text),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableHistory();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence? _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class MovieDB extends SqfEntityModelProvider {
  MovieDB() {
    databaseName = myDbModel.databaseName;
    password = myDbModel.password;
    dbVersion = myDbModel.dbVersion;
    preSaveAction = myDbModel.preSaveAction;
    logFunction = myDbModel.logFunction;
    databaseTables = [
      TableUser.getInstance,
      TableTicket.getInstance,
      TableHistory.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
    databasePath = myDbModel.databasePath;
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region User
class User extends TableBase {
  User({this.id, this.email, this.password, this.isSignIN}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  User.withFields(this.email, this.password, this.isSignIN) {
    _setDefaultValues();
  }
  User.withId(this.id, this.email, this.password, this.isSignIN) {
    _setDefaultValues();
  }
  // fromMap v2.0
  User.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['email'] != null) {
      email = o['email'].toString();
    }
    if (o['password'] != null) {
      password = o['password'].toString();
    }
    if (o['isSignIN'] != null) {
      isSignIN =
          o['isSignIN'].toString() == '1' || o['isSignIN'].toString() == 'true';
    }
  }
  // FIELDS (User)
  int? id;
  String? email;
  String? password;
  bool? isSignIN;

  // end FIELDS (User)

  static const bool _softDeleteActivated = false;
  UserManager? __mnUser;

  UserManager get _mnUser {
    return __mnUser = __mnUser ?? UserManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (email != null || !forView) {
      map['email'] = email;
    }
    if (password != null || !forView) {
      map['password'] = password;
    }
    if (isSignIN != null) {
      map['isSignIN'] = forQuery ? (isSignIN! ? 1 : 0) : isSignIN;
    } else if (isSignIN != null || !forView) {
      map['isSignIN'] = null;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (email != null || !forView) {
      map['email'] = email;
    }
    if (password != null || !forView) {
      map['password'] = password;
    }
    if (isSignIN != null) {
      map['isSignIN'] = forQuery ? (isSignIN! ? 1 : 0) : isSignIN;
    } else if (isSignIN != null || !forView) {
      map['isSignIN'] = null;
    }

    return map;
  }

  /// This method returns Json String [User]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [User]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [email, password, isSignIN];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [id, email, password, isSignIN];
  }

  static Future<List<User>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR User.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<User>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <User>[];
    try {
      objList = list
          .map((user) => User.fromMap(user as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR User.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<User>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<User> objList = <User>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = User.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns User by ID if exist, otherwise returns null
  /// Primary Keys: int? id
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [User] if exist, otherwise returns null
  Future<User?> getById(int? id,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (id == null) {
      return null;
    }
    User? obj;
    final data = await _mnUser.getById([id]);
    if (data.length != 0) {
      obj = User.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (User) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> save({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnUser.insert(this, ignoreBatch);
    } else {
      await _mnUser.update(this);
    }

    return id;
  }

  /// Saves the (User) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> saveOrThrow({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnUser.insertOrThrow(this, ignoreBatch);

      isInsert = true;
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnUser.updateOrThrow(this);
    }

    return id;
  }

  /// saveAs User. Returns a new Primary Key value of User

  /// <returns>Returns a new Primary Key value of User
  @override
  Future<int?> saveAs({bool ignoreBatch = true}) async {
    id = null;

    return save(ignoreBatch: ignoreBatch);
  }

  /// saveAll method saves the sent List<User> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<User> users,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await MovieDB().batchStart();
    for (final obj in users) {
      await obj.save(ignoreBatch: false);
    }
    if (!isStartedBatch) {
      result = await MovieDB().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
      for (int i = 0; i < users.length; i++) {
        if (users[i].id == null) {
          users[i].id = result![i] as int;
        }
      }
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns id
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnUser.rawInsert(
          'INSERT OR REPLACE INTO user (id, email, password, isSignIN)  VALUES (?,?,?,?)',
          [id, email, password, isSignIN],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true, successMessage: 'User id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'User id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'User Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<User>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(List<User> users,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    final results = await _mnUser.rawInsertAll(
        'INSERT OR REPLACE INTO user (id, email, password, isSignIN)  VALUES (?,?,?,?)',
        users,
        exclusive: exclusive,
        noResult: noResult,
        continueOnError: continueOnError);
    return results;
  }

  /// Deletes User

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete User invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnUser
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnUser.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [User] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  UserFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return UserFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  UserFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return UserFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isSignIN = isSignIN ?? true;
  }

  @override
  void rollbackPk() {
    if (isInsert == true) {
      id = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion user

// region UserField
class UserField extends FilterBase {
  UserField(UserFilterBuilder userFB) : super(userFB);

  @override
  UserFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder isNull() {
    return super.isNull() as UserFilterBuilder;
  }

  @override
  UserFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as UserFilterBuilder;
  }

  @override
  UserField get not {
    return super.not as UserField;
  }
}
// endregion UserField

// region UserFilterBuilder
class UserFilterBuilder extends ConjunctionBase {
  UserFilterBuilder(User obj, bool? getIsDeleted) : super(obj, getIsDeleted) {
    _mnUser = obj._mnUser;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  UserManager? _mnUser;

  /// put the sql keyword 'AND'
  @override
  UserFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  UserFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  UserFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  UserFilterBuilder where(String? whereCriteria, {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  UserFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  UserFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  UserFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  UserFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  UserFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  UserFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  UserFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  UserField _setField(UserField? field, String colName, DbType dbtype) {
    return UserField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  UserField? _id;
  UserField get id {
    return _id = _setField(_id, 'id', DbType.integer);
  }

  UserField? _email;
  UserField get email {
    return _email = _setField(_email, 'email', DbType.text);
  }

  UserField? _password;
  UserField get password {
    return _password = _setField(_password, 'password', DbType.text);
  }

  UserField? _isSignIN;
  UserField get isSignIN {
    return _isSignIN = _setField(_isSignIN, 'isSignIN', DbType.bool);
  }

  /// Deletes List<User> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnUser!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnUser!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'id IN (SELECT id from user ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnUser!.updateBatch(qparams, values);
  }

  /// This method always returns [User] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> User?
  @override
  Future<User?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnUser!.toList(qparams);
    final data = await objFuture;
    User? obj;
    if (data.isNotEmpty) {
      obj = User.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [User]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> User?
  @override
  Future<User> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        User();
  }

  /// This method returns int. [User]
  /// <returns>int
  @override
  Future<int> toCount([VoidCallback Function(int c)? userCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final usersFuture = await _mnUser!.toList(qparams);
    final int count = usersFuture[0]['CNT'] as int;
    if (userCount != null) {
      userCount(count);
    }
    return count;
  }

  /// This method returns List<User> [User]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<User>
  @override
  Future<List<User>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<User> usersData = await User.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return usersData;
  }

  /// This method returns Json String [User]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [User]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [User]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnUser!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [User]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM user WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  @override
  Future<List<int>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _mnUser!.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [User]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnUser!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await User.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnUser!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion UserFilterBuilder

// region UserFields
class UserFields {
  static TableField? _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField? _fEmail;
  static TableField get email {
    return _fEmail =
        _fEmail ?? SqlSyntax.setField(_fEmail, 'email', DbType.text);
  }

  static TableField? _fPassword;
  static TableField get password {
    return _fPassword =
        _fPassword ?? SqlSyntax.setField(_fPassword, 'password', DbType.text);
  }

  static TableField? _fIsSignIN;
  static TableField get isSignIN {
    return _fIsSignIN =
        _fIsSignIN ?? SqlSyntax.setField(_fIsSignIN, 'isSignIN', DbType.bool);
  }
}
// endregion UserFields

//region UserManager
class UserManager extends SqfEntityProvider {
  UserManager()
      : super(MovieDB(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'user';
  static const List<String> _primaryKeyList = ['id'];
  static const String _whereStr = 'id=?';
}

//endregion UserManager
// region Ticket
class Ticket extends TableBase {
  Ticket(
      {this.ticketID,
      this.movieID,
      this.customerName,
      this.email,
      this.customerID,
      this.contactNumber,
      this.movieTitle,
      this.url,
      this.movieStartTime,
      this.movieEndTime}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  Ticket.withFields(
      this.ticketID,
      this.movieID,
      this.customerName,
      this.email,
      this.customerID,
      this.contactNumber,
      this.movieTitle,
      this.url,
      this.movieStartTime,
      this.movieEndTime) {
    _setDefaultValues();
  }
  Ticket.withId(
      this.ticketID,
      this.movieID,
      this.customerName,
      this.email,
      this.customerID,
      this.contactNumber,
      this.movieTitle,
      this.url,
      this.movieStartTime,
      this.movieEndTime) {
    _setDefaultValues();
  }
  // fromMap v2.0
  Ticket.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    ticketID = int.tryParse(o['ticketID'].toString());
    if (o['movieID'] != null) {
      movieID = int.tryParse(o['movieID'].toString());
    }
    if (o['customerName'] != null) {
      customerName = o['customerName'].toString();
    }
    if (o['email'] != null) {
      email = o['email'].toString();
    }
    if (o['customerID'] != null) {
      customerID = int.tryParse(o['customerID'].toString());
    }
    if (o['contactNumber'] != null) {
      contactNumber = int.tryParse(o['contactNumber'].toString());
    }
    if (o['movieTitle'] != null) {
      movieTitle = o['movieTitle'].toString();
    }
    if (o['url'] != null) {
      url = o['url'].toString();
    }
    if (o['movieStartTime'] != null) {
      movieStartTime = int.tryParse(o['movieStartTime'].toString());
    }
    if (o['movieEndTime'] != null) {
      movieEndTime = int.tryParse(o['movieEndTime'].toString());
    }

    isSaved = true;
  }
  // FIELDS (Ticket)
  int? ticketID;
  int? movieID;
  String? customerName;
  String? email;
  int? customerID;
  int? contactNumber;
  String? movieTitle;
  String? url;
  int? movieStartTime;
  int? movieEndTime;
  bool? isSaved;
  // end FIELDS (Ticket)

  static const bool _softDeleteActivated = false;
  TicketManager? __mnTicket;

  TicketManager get _mnTicket {
    return __mnTicket = __mnTicket ?? TicketManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['ticketID'] = ticketID;
    if (movieID != null || !forView) {
      map['movieID'] = movieID;
    }
    if (customerName != null || !forView) {
      map['customerName'] = customerName;
    }
    if (email != null || !forView) {
      map['email'] = email;
    }
    if (customerID != null || !forView) {
      map['customerID'] = customerID;
    }
    if (contactNumber != null || !forView) {
      map['contactNumber'] = contactNumber;
    }
    if (movieTitle != null || !forView) {
      map['movieTitle'] = movieTitle;
    }
    if (url != null || !forView) {
      map['url'] = url;
    }
    if (movieStartTime != null || !forView) {
      map['movieStartTime'] = movieStartTime;
    }
    if (movieEndTime != null || !forView) {
      map['movieEndTime'] = movieEndTime;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['ticketID'] = ticketID;
    if (movieID != null || !forView) {
      map['movieID'] = movieID;
    }
    if (customerName != null || !forView) {
      map['customerName'] = customerName;
    }
    if (email != null || !forView) {
      map['email'] = email;
    }
    if (customerID != null || !forView) {
      map['customerID'] = customerID;
    }
    if (contactNumber != null || !forView) {
      map['contactNumber'] = contactNumber;
    }
    if (movieTitle != null || !forView) {
      map['movieTitle'] = movieTitle;
    }
    if (url != null || !forView) {
      map['url'] = url;
    }
    if (movieStartTime != null || !forView) {
      map['movieStartTime'] = movieStartTime;
    }
    if (movieEndTime != null || !forView) {
      map['movieEndTime'] = movieEndTime;
    }

    return map;
  }

  /// This method returns Json String [Ticket]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Ticket]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [
      ticketID,
      movieID,
      customerName,
      email,
      customerID,
      contactNumber,
      movieTitle,
      url,
      movieStartTime,
      movieEndTime
    ];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [
      ticketID,
      movieID,
      customerName,
      email,
      customerID,
      contactNumber,
      movieTitle,
      url,
      movieStartTime,
      movieEndTime
    ];
  }

  static Future<List<Ticket>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Ticket.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<Ticket>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Ticket>[];
    try {
      objList = list
          .map((ticket) => Ticket.fromMap(ticket as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Ticket.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Ticket>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<Ticket> objList = <Ticket>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Ticket.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Ticket by ID if exist, otherwise returns null
  /// Primary Keys: int? ticketID
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [Ticket] if exist, otherwise returns null
  Future<Ticket?> getById(int? ticketID,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (ticketID == null) {
      return null;
    }
    Ticket? obj;
    final data = await _mnTicket.getById([ticketID]);
    if (data.length != 0) {
      obj = Ticket.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Ticket) object. If the ticketID field is null, saves as a new record and returns new ticketID, if ticketID is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns ticketID
  @override
  Future<int?> save({bool ignoreBatch = true}) async {
    if (ticketID == null || ticketID == 0 || !isSaved!) {
      await _mnTicket.insert(this, ignoreBatch);
      if (saveResult!.success) {
        isSaved = true;
      }
    } else {
      await _mnTicket.update(this);
    }

    return ticketID;
  }

  /// Saves the (Ticket) object. If the ticketID field is null, saves as a new record and returns new ticketID, if ticketID is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns ticketID
  @override
  Future<int?> saveOrThrow({bool ignoreBatch = true}) async {
    if (ticketID == null || ticketID == 0 || !isSaved!) {
      await _mnTicket.insertOrThrow(this, ignoreBatch);
      if (saveResult != null && saveResult!.success) {
        isSaved = true;
      }
      isInsert = true;
    } else {
      // ticketID= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnTicket.updateOrThrow(this);
    }

    return ticketID;
  }

  /// saveAll method saves the sent List<Ticket> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Ticket> tickets,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await MovieDB().batchStart();
    for (final obj in tickets) {
      await obj.save(ignoreBatch: false);
    }
    if (!isStartedBatch) {
      result = await MovieDB().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns ticketID
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnTicket.rawInsert(
          'INSERT OR REPLACE INTO ticket (ticketID, movieID, customerName, email, customerID, contactNumber, movieTitle, url, movieStartTime, movieEndTime)  VALUES (?,?,?,?,?,?,?,?,?,?)',
          [
            ticketID,
            movieID,
            customerName,
            email,
            customerID,
            contactNumber,
            movieTitle,
            url,
            movieStartTime,
            movieEndTime
          ],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Ticket ticketID=$ticketID updated successfully');
      } else {
        saveResult = BoolResult(
            success: false,
            errorMessage: 'Ticket ticketID=$ticketID did not update');
      }
      return ticketID;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Ticket Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<Ticket>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(List<Ticket> tickets,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    final results = await _mnTicket.rawInsertAll(
        'INSERT OR REPLACE INTO ticket (ticketID, movieID, customerName, email, customerID, contactNumber, movieTitle, url, movieStartTime, movieEndTime)  VALUES (?,?,?,?,?,?,?,?,?,?)',
        tickets,
        exclusive: exclusive,
        noResult: noResult,
        continueOnError: continueOnError);
    return results;
  }

  /// Deletes Ticket

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete Ticket invoked (ticketID=$ticketID)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnTicket.delete(
          QueryParams(whereString: 'ticketID=?', whereArguments: [ticketID]));
    } else {
      return _mnTicket.updateBatch(
          QueryParams(whereString: 'ticketID=?', whereArguments: [ticketID]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [Ticket] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  TicketFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return TicketFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  TicketFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return TicketFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isSaved = false;
  }

  @override
  void rollbackPk() {
    if (isInsert == true) {
      ticketID = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion ticket

// region TicketField
class TicketField extends FilterBase {
  TicketField(TicketFilterBuilder ticketFB) : super(ticketFB);

  @override
  TicketFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as TicketFilterBuilder;
  }

  @override
  TicketFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as TicketFilterBuilder;
  }

  @override
  TicketFilterBuilder isNull() {
    return super.isNull() as TicketFilterBuilder;
  }

  @override
  TicketFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as TicketFilterBuilder;
  }

  @override
  TicketFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as TicketFilterBuilder;
  }

  @override
  TicketFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as TicketFilterBuilder;
  }

  @override
  TicketFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as TicketFilterBuilder;
  }

  @override
  TicketFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as TicketFilterBuilder;
  }

  @override
  TicketFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as TicketFilterBuilder;
  }

  @override
  TicketFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as TicketFilterBuilder;
  }

  @override
  TicketFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as TicketFilterBuilder;
  }

  @override
  TicketFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as TicketFilterBuilder;
  }

  @override
  TicketField get not {
    return super.not as TicketField;
  }
}
// endregion TicketField

// region TicketFilterBuilder
class TicketFilterBuilder extends ConjunctionBase {
  TicketFilterBuilder(Ticket obj, bool? getIsDeleted)
      : super(obj, getIsDeleted) {
    _mnTicket = obj._mnTicket;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  TicketManager? _mnTicket;

  /// put the sql keyword 'AND'
  @override
  TicketFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  TicketFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  TicketFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  TicketFilterBuilder where(String? whereCriteria, {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  TicketFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  TicketFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  TicketFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  TicketFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  TicketFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  TicketFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  TicketFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  TicketField _setField(TicketField? field, String colName, DbType dbtype) {
    return TicketField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  TicketField? _ticketID;
  TicketField get ticketID {
    return _ticketID = _setField(_ticketID, 'ticketID', DbType.integer);
  }

  TicketField? _movieID;
  TicketField get movieID {
    return _movieID = _setField(_movieID, 'movieID', DbType.integer);
  }

  TicketField? _customerName;
  TicketField get customerName {
    return _customerName =
        _setField(_customerName, 'customerName', DbType.text);
  }

  TicketField? _email;
  TicketField get email {
    return _email = _setField(_email, 'email', DbType.text);
  }

  TicketField? _customerID;
  TicketField get customerID {
    return _customerID = _setField(_customerID, 'customerID', DbType.integer);
  }

  TicketField? _contactNumber;
  TicketField get contactNumber {
    return _contactNumber =
        _setField(_contactNumber, 'contactNumber', DbType.integer);
  }

  TicketField? _movieTitle;
  TicketField get movieTitle {
    return _movieTitle = _setField(_movieTitle, 'movieTitle', DbType.text);
  }

  TicketField? _url;
  TicketField get url {
    return _url = _setField(_url, 'url', DbType.text);
  }

  TicketField? _movieStartTime;
  TicketField get movieStartTime {
    return _movieStartTime =
        _setField(_movieStartTime, 'movieStartTime', DbType.integer);
  }

  TicketField? _movieEndTime;
  TicketField get movieEndTime {
    return _movieEndTime =
        _setField(_movieEndTime, 'movieEndTime', DbType.integer);
  }

  /// Deletes List<Ticket> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnTicket!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnTicket!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'ticketID IN (SELECT ticketID from ticket ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnTicket!.updateBatch(qparams, values);
  }

  /// This method always returns [Ticket] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Ticket?
  @override
  Future<Ticket?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnTicket!.toList(qparams);
    final data = await objFuture;
    Ticket? obj;
    if (data.isNotEmpty) {
      obj = Ticket.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [Ticket]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Ticket?
  @override
  Future<Ticket> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        Ticket();
  }

  /// This method returns int. [Ticket]
  /// <returns>int
  @override
  Future<int> toCount([VoidCallback Function(int c)? ticketCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final ticketsFuture = await _mnTicket!.toList(qparams);
    final int count = ticketsFuture[0]['CNT'] as int;
    if (ticketCount != null) {
      ticketCount(count);
    }
    return count;
  }

  /// This method returns List<Ticket> [Ticket]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<Ticket>
  @override
  Future<List<Ticket>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<Ticket> ticketsData = await Ticket.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return ticketsData;
  }

  /// This method returns Json String [Ticket]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Ticket]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Ticket]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnTicket!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Ticket]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] =
        'SELECT `ticketID` FROM ticket WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  @override
  Future<List<int>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<int> ticketIDData = <int>[];
    qparams.selectColumns = ['ticketID'];
    final ticketIDFuture = await _mnTicket!.toList(qparams);

    final int count = ticketIDFuture.length;
    for (int i = 0; i < count; i++) {
      ticketIDData.add(ticketIDFuture[i]['ticketID'] as int);
    }
    return ticketIDData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Ticket]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnTicket!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await Ticket.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnTicket!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion TicketFilterBuilder

// region TicketFields
class TicketFields {
  static TableField? _fTicketID;
  static TableField get ticketID {
    return _fTicketID = _fTicketID ??
        SqlSyntax.setField(_fTicketID, 'ticketid', DbType.integer);
  }

  static TableField? _fMovieID;
  static TableField get movieID {
    return _fMovieID =
        _fMovieID ?? SqlSyntax.setField(_fMovieID, 'movieID', DbType.integer);
  }

  static TableField? _fCustomerName;
  static TableField get customerName {
    return _fCustomerName = _fCustomerName ??
        SqlSyntax.setField(_fCustomerName, 'customerName', DbType.text);
  }

  static TableField? _fEmail;
  static TableField get email {
    return _fEmail =
        _fEmail ?? SqlSyntax.setField(_fEmail, 'email', DbType.text);
  }

  static TableField? _fCustomerID;
  static TableField get customerID {
    return _fCustomerID = _fCustomerID ??
        SqlSyntax.setField(_fCustomerID, 'customerID', DbType.integer);
  }

  static TableField? _fContactNumber;
  static TableField get contactNumber {
    return _fContactNumber = _fContactNumber ??
        SqlSyntax.setField(_fContactNumber, 'contactNumber', DbType.integer);
  }

  static TableField? _fMovieTitle;
  static TableField get movieTitle {
    return _fMovieTitle = _fMovieTitle ??
        SqlSyntax.setField(_fMovieTitle, 'movieTitle', DbType.text);
  }

  static TableField? _fUrl;
  static TableField get url {
    return _fUrl = _fUrl ?? SqlSyntax.setField(_fUrl, 'url', DbType.text);
  }

  static TableField? _fMovieStartTime;
  static TableField get movieStartTime {
    return _fMovieStartTime = _fMovieStartTime ??
        SqlSyntax.setField(_fMovieStartTime, 'movieStartTime', DbType.integer);
  }

  static TableField? _fMovieEndTime;
  static TableField get movieEndTime {
    return _fMovieEndTime = _fMovieEndTime ??
        SqlSyntax.setField(_fMovieEndTime, 'movieEndTime', DbType.integer);
  }
}
// endregion TicketFields

//region TicketManager
class TicketManager extends SqfEntityProvider {
  TicketManager()
      : super(MovieDB(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'ticket';
  static const List<String> _primaryKeyList = ['ticketID'];
  static const String _whereStr = 'ticketID=?';
}

//endregion TicketManager
// region History
class History extends TableBase {
  History({this.movieID, this.url, this.searchAt, this.title}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  History.withFields(this.movieID, this.url, this.searchAt, this.title) {
    _setDefaultValues();
  }
  History.withId(this.movieID, this.url, this.searchAt, this.title) {
    _setDefaultValues();
  }
  // fromMap v2.0
  History.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    movieID = int.tryParse(o['movieID'].toString());
    if (o['url'] != null) {
      url = o['url'].toString();
    }
    if (o['searchAt'] != null) {
      searchAt = int.tryParse(o['searchAt'].toString());
    }
    if (o['title'] != null) {
      title = o['title'].toString();
    }

    isSaved = true;
  }
  // FIELDS (History)
  int? movieID;
  String? url;
  int? searchAt;
  String? title;
  bool? isSaved;
  // end FIELDS (History)

  static const bool _softDeleteActivated = false;
  HistoryManager? __mnHistory;

  HistoryManager get _mnHistory {
    return __mnHistory = __mnHistory ?? HistoryManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['movieID'] = movieID;
    if (url != null || !forView) {
      map['url'] = url;
    }
    if (searchAt != null || !forView) {
      map['searchAt'] = searchAt;
    }
    if (title != null || !forView) {
      map['title'] = title;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['movieID'] = movieID;
    if (url != null || !forView) {
      map['url'] = url;
    }
    if (searchAt != null || !forView) {
      map['searchAt'] = searchAt;
    }
    if (title != null || !forView) {
      map['title'] = title;
    }

    return map;
  }

  /// This method returns Json String [History]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [History]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [movieID, url, searchAt, title];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [movieID, url, searchAt, title];
  }

  static Future<List<History>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR History.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<History>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <History>[];
    try {
      objList = list
          .map((history) => History.fromMap(history as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR History.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<History>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<History> objList = <History>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = History.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns History by ID if exist, otherwise returns null
  /// Primary Keys: int? movieID
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [History] if exist, otherwise returns null
  Future<History?> getById(int? movieID,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (movieID == null) {
      return null;
    }
    History? obj;
    final data = await _mnHistory.getById([movieID]);
    if (data.length != 0) {
      obj = History.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (History) object. If the movieID field is null, saves as a new record and returns new movieID, if movieID is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns movieID
  @override
  Future<int?> save({bool ignoreBatch = true}) async {
    if (movieID == null || movieID == 0 || !isSaved!) {
      await _mnHistory.insert(this, ignoreBatch);
      if (saveResult!.success) {
        isSaved = true;
      }
    } else {
      await _mnHistory.update(this);
    }

    return movieID;
  }

  /// Saves the (History) object. If the movieID field is null, saves as a new record and returns new movieID, if movieID is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns movieID
  @override
  Future<int?> saveOrThrow({bool ignoreBatch = true}) async {
    if (movieID == null || movieID == 0 || !isSaved!) {
      await _mnHistory.insertOrThrow(this, ignoreBatch);
      if (saveResult != null && saveResult!.success) {
        isSaved = true;
      }
      isInsert = true;
    } else {
      // movieID= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnHistory.updateOrThrow(this);
    }

    return movieID;
  }

  /// saveAll method saves the sent List<History> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<History> histories,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await MovieDB().batchStart();
    for (final obj in histories) {
      await obj.save(ignoreBatch: false);
    }
    if (!isStartedBatch) {
      result = await MovieDB().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns movieID
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnHistory.rawInsert(
          'INSERT OR REPLACE INTO history (movieID, url, searchAt, title)  VALUES (?,?,?,?)',
          [movieID, url, searchAt, title],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'History movieID=$movieID updated successfully');
      } else {
        saveResult = BoolResult(
            success: false,
            errorMessage: 'History movieID=$movieID did not update');
      }
      return movieID;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'History Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<History>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(List<History> histories,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    final results = await _mnHistory.rawInsertAll(
        'INSERT OR REPLACE INTO history (movieID, url, searchAt, title)  VALUES (?,?,?,?)',
        histories,
        exclusive: exclusive,
        noResult: noResult,
        continueOnError: continueOnError);
    return results;
  }

  /// Deletes History

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete History invoked (movieID=$movieID)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnHistory.delete(
          QueryParams(whereString: 'movieID=?', whereArguments: [movieID]));
    } else {
      return _mnHistory.updateBatch(
          QueryParams(whereString: 'movieID=?', whereArguments: [movieID]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [History] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  HistoryFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return HistoryFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  HistoryFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return HistoryFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isSaved = false;
  }

  @override
  void rollbackPk() {
    if (isInsert == true) {
      movieID = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion history

// region HistoryField
class HistoryField extends FilterBase {
  HistoryField(HistoryFilterBuilder historyFB) : super(historyFB);

  @override
  HistoryFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as HistoryFilterBuilder;
  }

  @override
  HistoryFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as HistoryFilterBuilder;
  }

  @override
  HistoryFilterBuilder isNull() {
    return super.isNull() as HistoryFilterBuilder;
  }

  @override
  HistoryFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as HistoryFilterBuilder;
  }

  @override
  HistoryFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as HistoryFilterBuilder;
  }

  @override
  HistoryFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as HistoryFilterBuilder;
  }

  @override
  HistoryFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as HistoryFilterBuilder;
  }

  @override
  HistoryFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as HistoryFilterBuilder;
  }

  @override
  HistoryFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as HistoryFilterBuilder;
  }

  @override
  HistoryFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as HistoryFilterBuilder;
  }

  @override
  HistoryFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as HistoryFilterBuilder;
  }

  @override
  HistoryFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as HistoryFilterBuilder;
  }

  @override
  HistoryField get not {
    return super.not as HistoryField;
  }
}
// endregion HistoryField

// region HistoryFilterBuilder
class HistoryFilterBuilder extends ConjunctionBase {
  HistoryFilterBuilder(History obj, bool? getIsDeleted)
      : super(obj, getIsDeleted) {
    _mnHistory = obj._mnHistory;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  HistoryManager? _mnHistory;

  /// put the sql keyword 'AND'
  @override
  HistoryFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  HistoryFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  HistoryFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  HistoryFilterBuilder where(String? whereCriteria, {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  HistoryFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  HistoryFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  HistoryFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  HistoryFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  HistoryFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  HistoryFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  HistoryFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  HistoryField _setField(HistoryField? field, String colName, DbType dbtype) {
    return HistoryField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  HistoryField? _movieID;
  HistoryField get movieID {
    return _movieID = _setField(_movieID, 'movieID', DbType.integer);
  }

  HistoryField? _url;
  HistoryField get url {
    return _url = _setField(_url, 'url', DbType.text);
  }

  HistoryField? _searchAt;
  HistoryField get searchAt {
    return _searchAt = _setField(_searchAt, 'searchAt', DbType.integer);
  }

  HistoryField? _title;
  HistoryField get title {
    return _title = _setField(_title, 'title', DbType.text);
  }

  /// Deletes List<History> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnHistory!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnHistory!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'movieID IN (SELECT movieID from history ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnHistory!.updateBatch(qparams, values);
  }

  /// This method always returns [History] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> History?
  @override
  Future<History?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnHistory!.toList(qparams);
    final data = await objFuture;
    History? obj;
    if (data.isNotEmpty) {
      obj = History.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [History]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> History?
  @override
  Future<History> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        History();
  }

  /// This method returns int. [History]
  /// <returns>int
  @override
  Future<int> toCount([VoidCallback Function(int c)? historyCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final historiesFuture = await _mnHistory!.toList(qparams);
    final int count = historiesFuture[0]['CNT'] as int;
    if (historyCount != null) {
      historyCount(count);
    }
    return count;
  }

  /// This method returns List<History> [History]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<History>
  @override
  Future<List<History>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<History> historiesData = await History.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return historiesData;
  }

  /// This method returns Json String [History]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [History]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [History]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnHistory!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [History]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] =
        'SELECT `movieID` FROM history WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  @override
  Future<List<int>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<int> movieIDData = <int>[];
    qparams.selectColumns = ['movieID'];
    final movieIDFuture = await _mnHistory!.toList(qparams);

    final int count = movieIDFuture.length;
    for (int i = 0; i < count; i++) {
      movieIDData.add(movieIDFuture[i]['movieID'] as int);
    }
    return movieIDData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [History]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnHistory!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await History.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnHistory!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion HistoryFilterBuilder

// region HistoryFields
class HistoryFields {
  static TableField? _fMovieID;
  static TableField get movieID {
    return _fMovieID =
        _fMovieID ?? SqlSyntax.setField(_fMovieID, 'movieid', DbType.integer);
  }

  static TableField? _fUrl;
  static TableField get url {
    return _fUrl = _fUrl ?? SqlSyntax.setField(_fUrl, 'url', DbType.text);
  }

  static TableField? _fSearchAt;
  static TableField get searchAt {
    return _fSearchAt = _fSearchAt ??
        SqlSyntax.setField(_fSearchAt, 'searchAt', DbType.integer);
  }

  static TableField? _fTitle;
  static TableField get title {
    return _fTitle =
        _fTitle ?? SqlSyntax.setField(_fTitle, 'title', DbType.text);
  }
}
// endregion HistoryFields

//region HistoryManager
class HistoryManager extends SqfEntityProvider {
  HistoryManager()
      : super(MovieDB(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'history';
  static const List<String> _primaryKeyList = ['movieID'];
  static const String _whereStr = 'movieID=?';
}

//endregion HistoryManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o)? nextval]) async {
    final val = await MovieDBSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o)? currentval]) async {
    final val = await MovieDBSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o)? currentval]) async {
    final val = await MovieDBSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class MovieDBSequenceManager extends SqfEntityProvider {
  MovieDBSequenceManager() : super(MovieDB());
}
// END OF ENTITIES
